namespace GF.Asset
{
	public enum AssetKey
	{
		Prefabs_Box001_FBX,
		Prefabs_Box001_prefab,
		TestUI_TestUI_fui_bytes,
		TestUI2_TestUI2_fui_bytes,
		_001_startmenu_BG_png,
		_001_startmenu_btn_关闭1_png,
		_002_mainmenu_bg_弹框_png,
		_002_mainmenu_bg_背包_png,
		_002_mainmenu_bg_道具_png,
		_002_mainmenu_pic_个人信息_png,
		_002_mainmenu_任务_png,
		_002_mainmenu_商城_png,
		_002_mainmenu_战斗_png,
		_002_mainmenu_技能_png,
		_002_mainmenu_系统_png,
		_002_mainmenu_背包_png,
		装备_女性_靴子__2__png,
		_003_taskother_bg_任务_png,
		_003_taskother_NPC对话半身像288x347_png,
		Image_方正粗圆简体_ttf,
		UIPanel_BattlePanel_prefab,
		UIPanel_ItemMessagePanel_prefab,
		UIPanel_KnapsackPanel_prefab,
		UIPanel_MainMenuPanel_prefab,
		UIPanel_ShopPanel_prefab,
		UIPanel_SkillPanel_prefab,
		UIPanel_SystemPanel_prefab,
		UIPanel_TaskPanel_prefab,
	}
}